# Generated by Django 3.0.8 on 2021-05-21 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collname', models.CharField(default='', max_length=20, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('colldone', models.BooleanField(blank=True, default=False, null=True)),
                ('job_status', models.CharField(blank=True, choices=[('Pending', 'P'), ('In progress', 'I'), ('Finished', 'F')], default='Pending', max_length=11, null=True)),
                ('estimated_amount', models.FloatField(blank=True, default=0, null=True)),
                ('deposited_amount', models.FloatField(blank=True, default=0, null=True)),
                ('paid_option', models.BooleanField(blank=True, default=False, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_file', models.FileField(blank=True, upload_to='completed_files')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(blank=True, default=False, null=True)),
                ('collection_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typr_main.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProofImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='proofimage')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('collection_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typr_main.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('message', models.CharField(blank=True, default='Hello there, welcome to Typr. Your Easy solution to getting things done!', max_length=120, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='orderimage')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('typed', models.BooleanField(blank=True, default=False, null=True)),
                ('collection_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typr_main.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='Hello there, welcome to Typr.', max_length=120, null=True)),
                ('target', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='this_images', to='typr_main.Images'),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='typr_main.Images'),
        ),
        migrations.AddField(
            model_name='collection',
            name='completed_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='typr_main.Results'),
        ),
    ]
