# Generated by Django 3.0.8 on 2021-05-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='name',
        ),
    ]
