# Generated by Django 3.0.8 on 2021-05-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0002_remove_notification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customnotification',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
