# Generated by Django 3.0.8 on 2021-05-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0003_customnotification_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='orderimage'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, default='Hello there, welcome to Typewriter. Your Easy solution to getting things done!', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='proofimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='proofimage'),
        ),
    ]
