# Generated by Django 3.0.8 on 2021-05-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0004_auto_20210525_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
