# Generated by Django 3.0.8 on 2021-05-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0005_auto_20210525_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
