# Generated by Django 3.0.8 on 2021-05-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0006_auto_20210525_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
        migrations.AddField(
            model_name='images',
            name='task',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
