# Generated by Django 3.0.8 on 2021-05-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0007_auto_20210525_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='task',
        ),
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.TextField(blank=True, default='', max_length=120, null=True),
        ),
    ]
