# Generated by Django 3.0.8 on 2021-05-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0008_auto_20210525_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.BinaryField(blank=True, editable=True, max_length=12, null=True),
        ),
    ]
