# Generated by Django 3.0.8 on 2021-05-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0010_auto_20210525_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='imageby',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
