# Generated by Django 3.0.8 on 2021-05-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0011_auto_20210525_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='imageby',
            new_name='imageby1',
        ),
        migrations.AddField(
            model_name='images',
            name='imageby2',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='imageby3',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
