# Generated by Django 3.0.8 on 2021-05-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0012_auto_20210525_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='imageby4',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
