# Generated by Django 3.0.8 on 2021-05-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0014_auto_20210525_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proofimages',
            name='image',
        ),
        migrations.AddField(
            model_name='proofimages',
            name='imageby',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='proofimages',
            name='name',
            field=models.TextField(blank=True, default='', max_length=120, null=True),
        ),
    ]
