# Generated by Django 3.0.8 on 2021-05-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0015_auto_20210525_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='name',
            field=models.TextField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='c_file',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
