# Generated by Django 3.0.8 on 2021-05-27 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typr_main', '0017_results_ext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgConvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageby', models.TextField(blank=True, default='', null=True)),
                ('name', models.TextField(blank=True, default='', max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('typed', models.BooleanField(blank=True, default=False, null=True)),
                ('collection_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typr_main.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='I',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collname', models.CharField(default='', max_length=20, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
