# Generated by Django 3.0.8 on 2021-05-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0019_auto_20210527_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgconvert',
            name='imageby',
            field=models.TextField(blank=True, default='', max_length=120, null=True),
        ),
    ]
