# Generated by Django 3.0.8 on 2021-05-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0020_auto_20210527_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgconvert',
            name='imageby',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imgconvert',
            name='name',
            field=models.TextField(blank=True, default='', max_length=120, null=True),
        ),
    ]
