# Generated by Django 3.0.8 on 2021-05-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0021_auto_20210527_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgconvert',
            name='imageby',
            field=models.FileField(blank=True, null=True, upload_to='convertimages'),
        ),
    ]
