# Generated by Django 3.0.8 on 2021-05-27 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typr_main', '0022_auto_20210527_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofImgConvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageby', models.FileField(blank=True, null=True, upload_to='convertimages')),
                ('name', models.TextField(blank=True, default='', max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('typed', models.BooleanField(blank=True, default=False, null=True)),
                ('collection_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typr_main.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='I',
        ),
    ]
