# Generated by Django 3.0.8 on 2021-05-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0023_auto_20210527_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofimgconvert',
            name='imageby',
            field=models.FileField(blank=True, null=True, upload_to='convertproofimages'),
        ),
    ]
