# Generated by Django 3.0.8 on 2021-05-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0024_auto_20210527_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proofimgconvert',
            old_name='typed',
            new_name='accepted',
        ),
    ]
