# Generated by Django 3.0.8 on 2021-06-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0026_imgconvert_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='uploading',
            field=models.BooleanField(default=True),
        ),
    ]
