# Generated by Django 3.0.8 on 2021-07-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typr_main', '0027_collection_uploading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='uploading',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
